
// Justin Bieber Song Data

module.exports = [
   { 
       artistName: 'Justin Bieber',
       collectionName: 'My World',
       trackName: 'Bigger',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2009-11-17T08:00:00Z',
       trackTimeMillis: 197766,
    },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'Nothing Like Us',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 199782,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My World',
       trackName: 'First Dance (feat. Usher)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2009-11-17T08:00:00Z',
       trackTimeMillis: 222312,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'Die in Your Arms',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 237293,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'Maria',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 247493,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'Take You',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 220893,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'Believe',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 222560,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'Fall',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 248387,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'Thought of You',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 230107,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My Worlds Acoustic',
       trackName: 'Pray',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-08T08:00:00Z',
       trackTimeMillis: 212920,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'Be Alright',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 189653,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'Love Me Like You Do',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 279347,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My World 2.0 (Bonus Track Version)',
       trackName: 'Kiss and Tell',
       collectionPrice: 9.99,
       trackPrice: -1,
       releaseDate: '2010-03-23T07:00:00Z',
       trackTimeMillis: 226078,
       },
     { 
       artistName: 'Justin Bieber & Sean Kingston',
       collectionName: 'My World 2.0 (Bonus Track Version)',
       trackName: 'Eenie Meenie',
       collectionPrice: 9.99,
       trackPrice: -1,
       releaseDate: '2010-03-23T07:00:00Z',
       trackTimeMillis: 202590,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'As Long As You Love Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 221685,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'Out of Town Girl',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 213560,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'One Love',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 234493,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'She Don\'t Like the Lights',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 239867,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My World',
       trackName: 'Common Denominator (Bonus Track)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2009-11-17T08:00:00Z',
       trackTimeMillis: 248655,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe (Deluxe Edition)',
       trackName: 'Catching Feelings',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 234680,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'Boyfriend',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 187690,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Never Say Never (The Remixes)',
       trackName: 'Born to Be Somebody',
       collectionPrice: 8.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-14T08:00:00Z',
       trackTimeMillis: 181027,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'I Would',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 227359,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'Beauty and a Beat',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 144692,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'Be Alright',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 210341,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'Take You',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 179380,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'Fall',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 220977,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Drummer Boy (feat. Busta Rhymes)',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 225333,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'She Don\'t Like the Lights',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 215816,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'Yellow Raincoat',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 224105,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe Acoustic',
       trackName: 'All Around the World',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2013-01-29T08:00:00Z',
       trackTimeMillis: 156177,
       },
     { 
       artistName: 'Justin Bieber & Mariah Carey',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'All I Want for Christmas Is You (SuperFestive!) [Duet With Mariah Carey]',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 240333,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'One Time (My Heart Edition) - Single',
       trackName: 'One Time (My Heart Edition)',
       collectionPrice: 1.29,
       trackPrice: 1.29,
       releaseDate: '2009-12-21T08:00:00Z',
       trackTimeMillis: 191697,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Never Say Never (The Remixes)',
       trackName: 'That Should Be Me (Remix) [feat. Rascal Flatts]',
       collectionPrice: 8.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-14T08:00:00Z',
       trackTimeMillis: 230787,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Pray',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 212320,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Beauty and a Beat (feat. Nicki Minaj)',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 227987,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'As Long As You Love Me (feat. Big Sean)',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 229467,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Never Say Never (The Remixes)',
       trackName: 'Somebody to Love (Remix) [feat. Usher]',
       collectionPrice: 8.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-14T08:00:00Z',
       trackTimeMillis: 220160,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Christmas Love',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 206787,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Turn to You (Mother\'s Day Dedication) - Single',
       trackName: 'Turn to You (Mother\'s Day Dedication)',
       collectionPrice: 1.29,
       trackPrice: 1.29,
       releaseDate: '2012-05-11T07:00:00Z',
       trackTimeMillis: 219973,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Santa Claus Is Coming to Town',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 216747,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Fa La La (feat. Boyz II Men)',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 185560,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Never Say Never (The Remixes)',
       trackName: 'Up (Remix) [feat. Chris Brown]',
       collectionPrice: 8.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-14T08:00:00Z',
       trackTimeMillis: 235627,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Never Say Never (The Remixes)',
       trackName: 'Runaway Love (Kanye West Remix) [feat. Raekwon]',
       collectionPrice: 8.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-14T08:00:00Z',
       trackTimeMillis: 287333,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'The Christmas Song (Chestnuts Roasting On an Open Fire) [feat. Usher]',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 215160,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Home This Christmas (feat. The Band Perry)',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 204400,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'All Around the World (feat. Ludacris)',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 244547,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Christmas Eve',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 223613,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Boyfriend',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 171333,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My Worlds Acoustic',
       trackName: 'Never Say Never (feat. Jaden Smith)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-08T08:00:00Z',
       trackTimeMillis: 223000,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Only Thing I Ever Get for Christmas',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 192160,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Silent Night',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 169080,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Someday At Christmas',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 173040,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'All I Want Is You',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 216387,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe (Deluxe Edition)',
       trackName: 'Fa La La (feat. Boyz II Men) [A cappella]',
       collectionPrice: 14.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 175213,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Never Say Never (The Remixes)',
       trackName: 'Overboard (Live) [feat. Miley Cyrus]',
       collectionPrice: 8.99,
       trackPrice: -1,
       releaseDate: '2011-02-14T08:00:00Z',
       trackTimeMillis: 307880,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Die In Your Arms',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 237293,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Love Me Like You Do',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 279347,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe',
       trackName: 'Mistletoe',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 182947,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Be Alright',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 189653,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Right Here (feat. Drake)',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 204187,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Thought of You',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 230107,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Believe',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 220787,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Fall',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 248387,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Take You',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 220893,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'Catching Feelings',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 234680,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Believe',
       trackName: 'One Love',
       collectionPrice: 11.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 234493,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Now That\'s What I Call Music Vol. 44',
       trackName: 'As Long As You Love Me (feat. Big Sean)',
       collectionPrice: 9.99,
       trackPrice: -1,
       releaseDate: '2012-11-06T08:00:00Z',
       trackTimeMillis: 226653,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Now That\'s What I Call Music, Vol. 43',
       trackName: 'Boyfriend',
       collectionPrice: 9.99,
       trackPrice: -1,
       releaseDate: '2012-08-07T07:00:00Z',
       trackTimeMillis: 170547,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My Worlds Acoustic',
       trackName: 'Baby',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-08T08:00:00Z',
       trackTimeMillis: 215453,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My Worlds Acoustic',
       trackName: 'Down to Earth',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-08T08:00:00Z',
       trackTimeMillis: 243493,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My Worlds Acoustic',
       trackName: 'One Less Lonely Girl',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-08T08:00:00Z',
       trackTimeMillis: 237720,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My Worlds Acoustic',
       trackName: 'U Smile',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-08T08:00:00Z',
       trackTimeMillis: 196613,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My Worlds Acoustic',
       trackName: 'That Should Be Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-08T08:00:00Z',
       trackTimeMillis: 249067,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My Worlds Acoustic',
       trackName: 'Favorite Girl (Acoustic Version) [Live]',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-08T08:00:00Z',
       trackTimeMillis: 309893,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My Worlds Acoustic',
       trackName: 'One Time',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-08T08:00:00Z',
       trackTimeMillis: 186267,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'My Worlds Acoustic',
       trackName: 'Stuck In the Moment',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-02-08T08:00:00Z',
       trackTimeMillis: 198760,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe',
       trackName: 'Drummer Boy (feat. Busta Rhymes)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 225333,
        },
     { 
       artistName: 'Justin Bieber & Mariah Carey',
       collectionName: 'Under the Mistletoe',
       trackName: 'All I Want for Christmas Is You (SuperFestive!) [Duet with Mariah Carey]',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 240333,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe',
       trackName: 'Santa Claus Is Coming to Town',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 216747,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe',
       trackName: 'Fa La La (feat. Boyz II Men)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 185560,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe',
       trackName: 'All I Want Is You',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 216387,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe',
       trackName: 'Home This Christmas (feat. The Band Perry)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 204400,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe',
       trackName: 'Only Thing I Ever Get for Christmas',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 192160,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe',
       trackName: 'Christmas Eve',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 223613,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe',
       trackName: 'The Christmas Song (Chestnuts Roasting On an Open Fire) [feat. Usher]',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 215160,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Under the Mistletoe',
       trackName: 'Silent Night',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2011-11-01T07:00:00Z',
       trackTimeMillis: 169427,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Now That\'s What I Call Today\'s Christmas',
       trackName: 'Mistletoe',
       collectionPrice: 9.99,
       trackPrice: -1,
       releaseDate: '2012-09-25T07:00:00Z',
       trackTimeMillis: 182947,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat (feat. Nicki Minaj)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 368160,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Now That\'s What I Call Music, Vol. 35',
       trackName: 'Somebody to Love (Remix) [feat. Usher]',
       collectionPrice: 11.99,
       trackPrice: -1,
       releaseDate: '2010-08-31T07:00:00Z',
       trackTimeMillis: 217027,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Radio Disney Jams 12',
       trackName: 'One Time (My Heart Edition)',
       collectionPrice: 7.99,
       trackPrice: -1,
       releaseDate: '2010-03-30T07:00:00Z',
       trackTimeMillis: 190667,
     },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat (feat. Nicki Minaj)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 233253,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Boyfriend (Dada Life Remix) - Single',
       trackName: 'Boyfriend',
       collectionPrice: 1.29,
       trackPrice: 1.29,
       releaseDate: '2012-06-12T07:00:00Z',
       trackTimeMillis: 332253,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Now That\'s What I Call Music!, Vol. 34',
       trackName: 'Baby (feat. Ludacris)',
       collectionPrice: 11.99,
       trackPrice: -1,
       releaseDate: '2010-06-15T07:00:00Z',
       trackTimeMillis: 213898,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'NOW That\'s What I Call Music, Vol. 41, 42, 43 & 44',
       trackName: 'Boyfriend',
       collectionPrice: 34.99,
       trackPrice: -1,
       releaseDate: '2012-02-07T08:00:00Z',
       trackTimeMillis: 170547,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'NOW That\'s What I Call Music, Vol. 41, 42, 43 & 44',
       trackName: 'As Long As You Love Me (feat. Big Sean)',
       collectionPrice: 34.99,
       trackPrice: -1,
       releaseDate: '2012-02-07T08:00:00Z',
       trackTimeMillis: 226653,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Radio Disney Jams (15th B-Day Edition)',
       trackName: 'Baby (feat. Ludacris)',
       collectionPrice: 7.99,
       trackPrice: -1,
       releaseDate: '2011-08-16T07:00:00Z',
       trackTimeMillis: 216507,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 344720,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat (feat. Nicki Minaj)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 370667,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me (feat. Big Sean)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 280027,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat (feat. Nicki Minaj)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 207480,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Boyfriend (Remixes)',
       trackName: 'Boyfriend',
       collectionPrice: 7.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-12T07:00:00Z',
       trackTimeMillis: 224147,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat (feat. Nicki Minaj)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 239920,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat (feat. Nicki Minaj)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 450787,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat (feat. Nicki Minaj)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 442733,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Boyfriend (Remixes)',
       trackName: 'Boyfriend',
       collectionPrice: 7.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-12T07:00:00Z',
       trackTimeMillis: 267587,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 368133,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 211947,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 442787,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 370867,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 451013,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Beauty and a Beat (Remixes) [feat. Nicki Minaj]',
       trackName: 'Beauty and a Beat (feat. Nicki Minaj)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-12-11T08:00:00Z',
       trackTimeMillis: 442787,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 306960,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 238107,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Boyfriend (Remixes)',
       trackName: 'Boyfriend',
       collectionPrice: 7.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-12T07:00:00Z',
       trackTimeMillis: 418080,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Boyfriend (Remixes)',
       trackName: 'Boyfriend',
       collectionPrice: 7.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-12T07:00:00Z',
       trackTimeMillis: 188000,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me (feat. Big Sean)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 280933,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 463013,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Boyfriend (Remixes)',
       trackName: 'Boyfriend',
       collectionPrice: 7.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-12T07:00:00Z',
       trackTimeMillis: 466400,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Boyfriend (Remixes)',
       trackName: 'Boyfriend',
       collectionPrice: 7.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-12T07:00:00Z',
       trackTimeMillis: 286240,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Boyfriend (Remixes)',
       trackName: 'Boyfriend',
       collectionPrice: 7.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-12T07:00:00Z',
       trackTimeMillis: 402787,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me (feat. Big Sean)',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 245720,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'Boyfriend (Remixes)',
       trackName: 'Boyfriend',
       collectionPrice: 7.99,
       trackPrice: 1.29,
       releaseDate: '2012-06-12T07:00:00Z',
       trackTimeMillis: 267587,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 237853,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 307053,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 300733,
        },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'As Long As You Love Me (Remixes) [feat. Big Sean]',
       trackName: 'As Long As You Love Me',
       collectionPrice: 9.99,
       trackPrice: 1.29,
       releaseDate: '2012-09-11T07:00:00Z',
       trackTimeMillis: 448187,
        },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'One Less Lonely Girl (Unplugged) - Single',
       trackName: 'One Less Lonely Girl (Unplugged)',
       collectionPrice: 0.99,
       trackPrice: 0.99,
       releaseDate: '2009-10-26T07:00:00Z',
       trackTimeMillis: 233087,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'One Time - Single',
       trackName: 'One Time',
       collectionPrice: 0.99,
       trackPrice: 0.99,
       releaseDate: '2010-01-09T08:00:00Z',
       trackTimeMillis: 240148,
       },
     { 
       artistName: 'Justin Bieber',
       collectionName: 'The Best Handsup Floorfillers',
       trackName: 'Switch (feat. Limi)',
       collectionPrice: 7.99,
       trackPrice: 0.99,
       releaseDate: '2013-07-12T07:00:00Z',
       trackTimeMillis: 212625,
        },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'Baby - (Made Famous By Justin Bieber)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 213522,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'One Less Lonely Girl - (Made Famous By Justin Bieber)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 233087,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Baby (Unplugged) - Single',
       trackName: 'Baby (Unplugged) - Single',
       collectionPrice: 0.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-03T08:00:00Z',
       trackTimeMillis: 213522,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Never Say Never (Acoustic) - Single',
       trackName: 'Never Say Never (Acoustic)',
       collectionPrice: 0.99,
       trackPrice: 0.99,
       releaseDate: '2010-11-02T07:00:00Z',
       trackTimeMillis: 220800,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'Today Was a Fairytale - (Made Famous By Taylor Swift)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 245729,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Never Let You Go (Unplugged) - Single',
       trackName: 'Never Let You Go (Unplugged) - Single',
       collectionPrice: 0.99,
       trackPrice: 0.99,
       releaseDate: '2010-03-24T07:00:00Z',
       trackTimeMillis: 262181,
       },
     { 
       artistName: 'Hot Beats - Tribute To Justin Bieber',
       collectionName: 'Believe (Instrumental) (Originally by Justin Bieber) - Single',
       trackName: 'Believe (Justin Bieber Instrumental Tribute)',
       collectionPrice: 0.99,
       trackPrice: 0.99,
       releaseDate: '2012-06-19T07:00:00Z',
       trackTimeMillis: 209789,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'One Time - (Made Famous By Justin Bieber)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 240148,
       },
     { 
       artistName: 'Made famous by Justin Bieber',
       collectionName: 'Sing to the world (Karaoke)',
       trackName: 'Pray',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2011-03-01T08:00:00Z',
       trackTimeMillis: 210907,
        },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'You\'ll Always Find Your Way Back Home - (Made Famous By Hannah Montana)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 224755,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'You Belong With Me - (Made Famous By Taylor Swift)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 228248,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'Fire Burning - (Made Famous By Sean Kingston)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 235608,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'Falling Down - (Made Famous By Selena Gomez)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 183667,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'Don\'t Forget - (Made Famous By Demi Lovato)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 211121,
       },
     { 
       artistName: 'Made famous by Justin Bieber',
       collectionName: '22 top songs 2011 (Karaoke)',
       trackName: 'Never say never',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2011-03-28T07:00:00Z',
       trackTimeMillis: 221046,
        },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'See You Again - (Made Famous By Miley Cyrus)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 189796,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'Love Story - (Made Famous By Taylor Swift)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 219347,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'One and the Same - (Made Famous By Selena Gomez)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 176780,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'Burnin\' Up - (Made Famous By the Jonas Brothers)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 211903,
       },
     { 
       artistName: 'The Justin Bieber Tribute Band',
       collectionName: 'Teen Hits - Unplugged',
       trackName: 'S.O.S. - (Made Famous By The Jonas Brothers)',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2010-02-24T08:00:00Z',
       trackTimeMillis: 139931,
       },
     { 
       artistName: 'Justin Bieber\'s Karaoke Band',
       collectionName: 'Karaoke Golden Collection 2011',
       trackName: 'Pray (Made famous by Justin Bieber)',
       collectionPrice: 7.92,
       trackPrice: 0.99,
       releaseDate: '2011-08-05T07:00:00Z',
       trackTimeMillis: 210907,
        },
     { 
       artistName: 'Karaoke Believers - Tribute to Justin Bieber',
       collectionName: 'One Love (Instrumental Tribute to Justin Bieber) - Single',
       trackName: 'One Love (Justin Bieber Instrumental Tribute)',
       collectionPrice: 0.99,
       trackPrice: 0.99,
       releaseDate: '2012-06-18T07:00:00Z',
       trackTimeMillis: 225045,
       },
     { 
       artistName: 'Made famous by Justin Bieber & Ludacris',
       collectionName: 'Karaoke The Best Collection',
       trackName: 'Baby',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2011-03-14T07:00:00Z',
       trackTimeMillis: 213870,
        },
     { 
       artistName: 'Made famous by Justin Bieber',
       collectionName: 'Top Hits 2011',
       trackName: 'Pray',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2011-04-26T07:00:00Z',
       trackTimeMillis: 210965,
        },
     { 
       artistName: 'Made famous by Justin Bieber',
       collectionName: 'Sing to the world (Karaoke)',
       trackName: 'Never say never',
       collectionPrice: 9.99,
       trackPrice: 0.99,
       releaseDate: '2011-03-01T08:00:00Z',
       trackTimeMillis: 221046,
        },
     { 
       artistName: 'The Belieber - Tribute To Justin Bieber',
       collectionName: 'Die In Your Arms - Piano Tribute to Justin Bieber - Single',
       trackName: 'Die In Your Arms - Piano Cover',
       collectionPrice: 0.99,
       trackPrice: 0.99,
       releaseDate: '2012-06-05T07:00:00Z',
       trackTimeMillis: 167458,
       },
     { 
       artistName: 'Made famous by Justin Bieber',
       collectionName: 'Baby - Single',
       trackName: 'Baby',
       collectionPrice: 0.99,
       trackPrice: 0.99,
       releaseDate: '2011-05-04T07:00:00Z',
       trackTimeMillis: 213917,
      }
];
